#!/usr/bin/env python3
"""Disable the poll workflow schedule once all Wahlkreise are complete."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Remove the schedule trigger from a workflow when no Wahlkreise are pending."
    )
    parser.add_argument(
        "--status-csv",
        required=True,
        type=Path,
        help="Path to data/.../wahlkreis-status.csv generated by the poller.",
    )
    parser.add_argument(
        "--workflow-path",
        required=True,
        type=Path,
        help="Path to the workflow YAML file that should lose its schedule trigger.",
    )
    return parser.parse_args()


def count_pending_wahlkreise(status_csv: Path) -> int:
    with status_csv.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        return sum(1 for row in reader if (row.get("status") or "").strip() == "pending")


def remove_schedule_block(workflow_text: str) -> tuple[str, bool]:
    lines = workflow_text.splitlines(keepends=True)
    output: list[str] = []
    in_on_section = False
    skipping_schedule = False
    changed = False

    for line in lines:
        stripped = line.strip()
        indent = len(line) - len(line.lstrip(" "))
        is_comment = stripped.startswith("#")

        if in_on_section and skipping_schedule:
            if stripped and not is_comment and indent <= 2:
                skipping_schedule = False
            else:
                continue

        if in_on_section and stripped and not is_comment and indent == 0 and not line.startswith("on:"):
            in_on_section = False

        if line.startswith("on:"):
            in_on_section = True

        if in_on_section and line.startswith("  schedule:"):
            skipping_schedule = True
            changed = True
            continue

        output.append(line)

    return "".join(output), changed


def main() -> int:
    args = parse_args()
    pending_wahlkreise = count_pending_wahlkreise(args.status_csv)
    print(f"Pending Wahlkreise: {pending_wahlkreise}")
    if pending_wahlkreise != 0:
        print("Schedule stays enabled.")
        return 0

    original = args.workflow_path.read_text(encoding="utf-8")
    updated, changed = remove_schedule_block(original)
    if not changed:
        print("Workflow schedule already removed.")
        return 0

    args.workflow_path.write_text(updated, encoding="utf-8")
    print(f"Removed schedule trigger from {args.workflow_path}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
